main:
  class: cad.main.MainAssembly
  config: {}
x-axis:
  class: cad.x_axis.XAxisAssembly
  config: {}
frame:
  class: cad.frame.FrameAssembly
  config: {}
knob:
  class: cad.frame.Knob
  config: {}
  export: true
bed:
  class: cad.bed.BedAssembly
  config: {}
lead-screw:
  class: cad.hardware.LeadScrew
  config:
    length: 100
bed-bearing-mount:
  class: cad.bed.BedBearingMount
  config: {}
